from enum import Enum

xml_name = "ComicInfo.xml"


class YesNo(Enum):
    UNKNOWN = 'Unknown'
    NO = 'No'
    YES = 'Yes'


class Manga(Enum):
    UNKNOWN = 'Unknown'
    NO = 'No'
    YES = 'Yes'
    RIGHT_LEFT = 'YesAndRightToLeft'


class PageType(Enum):
    FRONT_COVER = 'FrontCover'
    INNER_COVER = 'InnerCover'
    ROUNDUP = 'Roundup'
    STORY = 'Story'
    ADVERTISEMENT = 'Advertisement'
    EDITORIAL = 'Editorial'
    LETTERS = 'Letters'
    PREVIEW = 'Preview'
    BACK_COVER = 'BackCover'
    OTHER = 'Other'
    DELETED = 'Deleted'


class AgeRating(Enum):
    UNKNOWN = 'Unknown'
    ADULTS18 = 'Adults Only 18+'
    CHILDHOOD = 'Early Childhood'
    EVERYONE = 'Everyone'
    EVERYONE10 = 'Everyone 10+'
    G = 'G'
    KIDS = 'Kids to Adults'
    M = 'M'
    MA15 = 'MA15+'
    MATURE17 = 'Mature 17+'
    PG = 'PG'
    R18 = 'R18+'
    PENDING = 'Rating Pending'
    TEEN = 'Teen'
    X18 = 'X18+'


class Format(Enum):
    UNKNOWN = 'Unknown'
    # ONE_SHOT = '1 Shot'
    # ONE_SHOT = '1/2',
    # ONE_SHOT = '1-Shot'
    ANNOTATION = 'Annotation'
    # ANNOTATIONS = 'Annotations'
    ANNUAL = 'Annual'
    ANTHOLOGY = 'Anthology'
    # BLACK_WHITE = 'B&W'
    # BLACK_WHITE = 'B/W'
    # BLACK_WHITE = 'B&&W'
    BLACK_WHITE = 'Black & White'
    # BOX_SET = 'Box Set'
    BOX_SET = 'Box-Set'
    CROSSOVER = 'Crossover'
    DIRECTOR_CUT = 'Director\'s Cut'
    EPILOGUE = 'Epilogue'
    EVENT = 'Event'
    FCBD = 'FCBD'
    FLYER = 'Flyer'
    # GIANT_SIZE = 'Giant'
    # GIANT_SIZE = 'Giant Size'
    GIANT_SIZE = 'Giant-Size'
    GRAPHIC_NOVEL = 'Graphic Novel'
    # HARDCOVER = 'Hardcover'
    HARDCOVER = 'Hard-Cover'
    # KING_SIZE = 'King'
    # KING_SIZE = 'King Size'
    KING_SIZE = 'King-Size'
    LIMITED_SERIES = 'Limited Series'
    MAGAZINE = 'Magazine'
    NSFW = 'NSFW'
    # ONE_SHOT = 'One Shot'
    ONE_SHOT = 'One-Shot'
    POINT1 = 'Point 1'
    PREVIEW = 'Preview'
    PROLOGUE = 'Prologue'
    REFERENCE = 'Reference'
    REVIEW = 'Review'
    REVIEWED = 'Reviewed'
    SCANLATION = 'Scanlation'
    SCRIPT = 'Script'
    SERIES = 'Series'
    SKETCH = 'Sketch'
    SPECIAL = 'Special'
    # TRADE_PAPER_BACK = 'TPB'
    TRADE_PAPER_BACK = 'Trade Paper Back'
    # WEB_COMIC = 'WebComic'
    WEB_COMIC = 'Web Comic'
    # YEAR_ONE = 'Year 1'
    YEAR_ONE = 'Year One'
